# Generated by Django 4.0.5 on 2022-06-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment_data_of_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_of_comment',
            new_name='data',
        ),
    ]
